#!/usr/bin/env node
// Regenerates src/generated/schema.ts from the SDK spec in the sibling cexy-api-spec repo.
// Usage: node scripts/generate.mjs [--check]
//   --check  fail (exit 1) if the committed file differs from a fresh generation.
// The spec location can be overridden with CEXY_API_SPEC_DIR.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const specDir = resolve(root, process.env.CEXY_API_SPEC_DIR ?? "../cexy-api-spec");
const specPath = resolve(specDir, "spec/openapi.sdk.json");
const outPath = resolve(root, "src/generated/schema.ts");

if (!existsSync(specPath)) {
  console.error(`SDK spec not found at ${specPath}. Check out cexy-api-spec next to this repo or set CEXY_API_SPEC_DIR.`);
  process.exit(2);
}

const spec = JSON.parse(readFileSync(specPath, "utf8"));
const ast = await openapiTS(spec, { alphabetize: true, exportType: false });
const header =
  "/* eslint-disable */\n" +
  "// GENERATED by scripts/generate.mjs from cexy-api-spec/spec/openapi.sdk.json. Do not edit by hand.\n" +
  `// Spec info.version: ${spec.info?.version ?? "unknown"}\n\n`;
const out = header + astToString(ast);

if (process.argv.includes("--check")) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== out) {
    console.error("src/generated/schema.ts is out of date. Run `npm run generate` and commit the result.");
    process.exit(1);
  }
  console.log("generated types are up to date");
} else {
  writeFileSync(outPath, out);
  console.log(`wrote ${outPath.slice(root.length + 1)}`);
}
